services:
  database:
    image: mariadb:10.7.3
    container_name: mariadb1073
    restart: always
    environment:     
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./dbdata:/var/lib/mysql
