services:
  database:
    image: mysql:8.0.28
    container_name: mysql8
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
#     MYSQL_DATABASE: 'db'   
#      MYSQL_USER: 'user'
#      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
#      MYSQL_ROOT_HOST: '%' 
    ports:
      - '3306:3306'
#   user: 999:999
    volumes:
#      - ~/mysql/mysqldata:/var/lib/mysql
#      - ~/apps/mariadb/data:/var/lib/mysql
      - ./dbdata:/var/lib/mysql
