services:
 mongodb:
  image : mongo:4.4.12
  container_name: mongodb4
 # environment:
 # - PUID=1000
 # - PGID=1000
  volumes:
  - ./mongodata:/data/db
  ports:
  - 27017:27017
  restart: unless-stopped
