services:
  database:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    environment:
#      MYSQL_DATABASE: 'db'   
#      MYSQL_USER: 'user'
#      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
#      MYSQL_ROOT_HOST: '%' 
    ports:
      - '3306:3306'
    volumes:
#      - ~/mysql/mysqldata:/var/lib/mysql
#      - ~/apps/mariadb/data:/var/lib/mysql
      - ./dbdata:/var/lib/mysql
