services:
  database:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./dbdata:/var/lib/mysql
